#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate 16x16 Chinese font data (hz16[]) for STM32 LCD.
Output format: GB2312 index + 32-byte bitmap per character.
Bitmap layout: 16 rows x 2 bytes/row, MSB first, row-major.
Matches Gui_DrawFont_F16() decoding in GUI.c
"""
from PIL import Image, ImageDraw, ImageFont
import sys
import os

# Characters needed for demo (common answer/defense terms)
CHARS = "光通信可见接收发送号链路正常异文本图像音频调试待机数据帧错对率系统设备硬件版本功能显示状态传输误码稳定无线应用按键切换模式成功嵌入式物联网处理算法协议编解感采集波特灵敏距离范围滤放校验实时中断低耗节点终端服务演方案目标环境安全电子开关灯温湿源压流识别有效优化停失度"

# Font file - try common Windows Chinese fonts
FONT_PATHS = [
    "C:/Windows/Fonts/simhei.ttf",   # 黑体
    "C:/Windows/Fonts/simsun.ttc",   # 宋体
    "C:/Windows/Fonts/msyh.ttc",     # 微软雅黑
]

def find_font():
    for p in FONT_PATHS:
        if os.path.exists(p):
            return p
    raise FileNotFoundError("No Chinese font found in C:/Windows/Fonts/")

def char_to_bitmap(char, font_path):
    """Render a single character to 16x16 bitmap, return 32 bytes."""
    # Create a 16x16 image with white background
    img = Image.new('L', (16, 16), 255)  # white bg
    draw = ImageDraw.Draw(img)
    font = ImageFont.truetype(font_path, 16)

    # Get character bounding box to center it
    bbox = draw.textbbox((0, 0), char, font=font)
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]
    # Center the character
    x = (16 - w) // 2 - bbox[0]
    y = (16 - h) // 2 - bbox[1]
    draw.text((x, y), char, fill=0, font=font)  # black text

    # Convert to 32-byte bitmap
    pixels = img.load()
    msk = []
    for row in range(16):
        left_byte = 0
        right_byte = 0
        for col in range(8):
            # pixel < 128 = black (foreground)
            if pixels[col, row] < 128:
                left_byte |= (0x80 >> col)
        for col in range(8):
            if pixels[col + 8, row] < 128:
                right_byte |= (0x80 >> col)
        msk.append(left_byte)
        msk.append(right_byte)
    return msk

def get_gb2312_bytes(char):
    """Get GB2312 encoding (2 bytes) for a Chinese character."""
    try:
        return char.encode('gb2312')
    except UnicodeEncodeError:
        # Fallback to gbk
        return char.encode('gbk')

def generate_array(name, chars, font_path):
    """Generate a C array for given character set."""
    # Deduplicate while preserving order
    seen = set()
    unique_chars = []
    for c in chars:
        if c not in seen:
            seen.add(c)
            unique_chars.append(c)

    print(f"/* 16x16 Chinese font ({name}) - auto-generated by gen_hz16.py */")
    print(f"/* {len(unique_chars)} characters: {''.join(unique_chars)} */")
    print()
    print("const struct typFNT_GB162 " + name + "[] = {")

    for char in unique_chars:
        gb = get_gb2312_bytes(char)
        msk = char_to_bitmap(char, font_path)

        hex_msk = ",".join(f"0x{b:02X}" for b in msk)
        print(f'    /* "{char}" GB2312: 0x{gb[0]:02X}0x{gb[1]:02X} */')
        print(f'    {{{{0x{gb[0]:02X},0x{gb[1]:02X}}},{{{hex_msk}}}}},')

    print("};")
    print()
    return unique_chars

def main():
    font_path = find_font()
    print(f"// Using font: {font_path}")
    print()

    # Generate hz16[] - merged Chinese font array
    chars = generate_array("hz16", CHARS, font_path)
    print(f"#define hz16_num {len(chars)}")

    # Summary for verification
    print(f"// Total: {len(chars)} chars x 32 bytes = {len(chars)*32} bytes", file=sys.stderr)

if __name__ == "__main__":
    main()
