#!/usr/bin/env python3
"""
img2bmp.py - 将 JPG/PNG 图片转换为 128x128 1-bit bitmap C 数组

用于 2ASK 光通信系统的 TX 端图像数据生成。
输出格式与 logo.c 一致：128行 x 16字节 = 2048字节，
每像素1位，0=黑点，1=白点，MSB优先。

用法：
    python img2bmp.py input.jpg [output.c] [--var name] [--threshold 128]
    python img2bmp.py input.png output.c --var mickey_bitmap --threshold 128
"""

import sys
import os
import argparse

try:
    from PIL import Image
except ImportError:
    print("需要 Pillow 库: pip install Pillow")
    sys.exit(1)


def img_to_bitmap(img_path, size=128, threshold=128):
    """将图片转换为 128x128 1-bit bitmap 数据

    Args:
        img_path: 输入图片路径
        size: 输出尺寸（正方形，默认128）
        threshold: 二值化阈值（0-255），低于此值为黑点

    Returns:
        bytes: 2048字节的 1-bit bitmap 数据
    """
    img = Image.open(img_path)

    # 转灰度
    img = img.convert('L')

    # 缩放到 128x128（保持比例，居中填充白底）
    img = img.resize((size, size), Image.LANCZOS)

    # 二值化：灰度 < threshold → 0(黑)，>= threshold → 1(白)
    pixels = list(img.getdata())

    bitmap = bytearray(size * size // 8)  # 2048 bytes

    for row in range(size):
        for col in range(size):
            gray = pixels[row * size + col]
            bit = 1 if gray >= threshold else 0  # 白=1，黑=0

            byte_idx = row * (size // 8) + col // 8
            bit_pos = 7 - (col % 8)  # MSB优先

            if bit:
                bitmap[byte_idx] |= (1 << bit_pos)
            else:
                bitmap[byte_idx] &= ~(1 << bit_pos)

    return bytes(bitmap)


def generate_c_file(bitmap_data, var_name, width=128, height=128):
    """生成 C 数组源文件内容

    Args:
        bitmap_data: 1-bit bitmap 二进制数据
        var_name: C 变量名
        width: 图像宽度
        height: 图像高度

    Returns:
        str: C 源文件内容
    """
    size = len(bitmap_data)
    total_frames = (size + 63) // 64

    lines = []
    lines.append('/* Auto-generated by img2bmp.py */')
    lines.append('#include <stdint.h>')
    lines.append('')
    lines.append(f'#define {var_name.upper()}_WIDTH  {width}')
    lines.append(f'#define {var_name.upper()}_HEIGHT {height}')
    lines.append(f'#define {var_name.upper()}_SIZE   {size}  /* bytes */')
    lines.append(f'#define {var_name.upper()}_FRAMES {total_frames}')
    lines.append('')
    lines.append(f'const uint8_t {var_name}[{size}] = {{')

    # 每行16字节，与 logo.c 格式一致
    for i in range(0, size, 16):
        chunk = bitmap_data[i:i+16]
        hex_str = ', '.join(f'0x{b:02X}' for b in chunk)
        lines.append(f'    {hex_str},')

    lines.append('};')

    return '\n'.join(lines)


def generate_h_file(var_name, width=128, height=128, size=2048):
    """生成 C 头文件内容"""
    total_frames = (size + 63) // 64
    guard = f'__{var_name.upper()}_H__'

    lines = []
    lines.append(f'#ifndef {guard}')
    lines.append(f'#define {guard}')
    lines.append('')
    lines.append('#include <stdint.h>')
    lines.append('')
    lines.append(f'#define {var_name.upper()}_WIDTH  {width}')
    lines.append(f'#define {var_name.upper()}_HEIGHT {height}')
    lines.append(f'#define {var_name.upper()}_SIZE   {size}  /* bytes */')
    lines.append(f'#define {var_name.upper()}_FRAMES {total_frames}')
    lines.append('')
    lines.append(f'extern const uint8_t {var_name}[{size}];')
    lines.append('')
    lines.append(f'#endif /* {guard} */')

    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(
        description='将 JPG/PNG 图片转换为 128x128 1-bit bitmap C 数组')
    parser.add_argument('input', help='输入图片路径 (JPG/PNG)')
    parser.add_argument('output', nargs='?', default=None,
                        help='输出 .c 文件路径 (默认: 输入名_bitmap.c)')
    parser.add_argument('--var', default=None,
                        help='C 变量名 (默认: 从输入文件名派生)')
    parser.add_argument('--threshold', type=int, default=128,
                        help='二值化阈值 0-255 (默认: 128)')
    parser.add_argument('--header', action='store_true',
                        help='同时生成 .h 头文件')
    parser.add_argument('--invert', action='store_true',
                        help='反转黑白 (0=白, 1=黑)')

    args = parser.parse_args()

    # 变量名
    if args.var:
        var_name = args.var
    else:
        basename = os.path.splitext(os.path.basename(args.input))[0]
        var_name = basename.lower().replace('-', '_').replace(' ', '_') + '_bitmap'

    # 输出路径
    if args.output:
        out_c = args.output
    else:
        out_c = var_name + '.c'

    out_h = os.path.splitext(out_c)[0] + '.h'

    # 转换
    print(f'转换: {args.input} → {var_name}[] (阈值={args.threshold})')
    bitmap = img_to_bitmap(args.input, threshold=args.threshold)

    # 如果反转
    if args.invert:
        bitmap = bytes(b ^ 0xFF for b in bitmap)

    # 统计黑白像素比例
    black_count = sum(1 for b in bitmap for i in range(8) if not (b >> (7-i) & 1))
    total_pixels = 128 * 128
    print(f'像素统计: {black_count}/{total_pixels} 黑点 ({black_count*100//total_pixels}%)')

    # 生成 .c
    c_content = generate_c_file(bitmap, var_name)
    with open(out_c, 'w', encoding='utf-8') as f:
        f.write(c_content)
    print(f'已生成: {out_c} ({len(bitmap)} bytes)')

    # 生成 .h
    if args.header:
        h_content = generate_h_file(var_name)
        with open(out_h, 'w', encoding='utf-8') as f:
            f.write(h_content)
        print(f'已生成: {out_h}')

    print('完成！')


if __name__ == '__main__':
    main()
